CREATE TABLE pet (
    ID_PET SERIAL PRIMARY KEY,
    NO_PET VARCHAR(100) NOT NULL,
    NO_ESPECIE VARCHAR(50) NOT NULL,
    NO_RACA VARCHAR(50),
    NU_IDADE INT,
    NU_PESO NUMERIC(10,2),
    NO_DONO VARCHAR(100) NOT NULL
);
